	     <div class="container-fluid">
                 <ul class="nav navbar-nav hidden-xs">
				 
		   <a href="#" data-toggle="sidebar-menu" id="toggle-sidebar-menu" class="visible-xs"><i class="fa fa-bars fa-2x"></i></a>

			   	<?php
if ($fullname != false)
  foreach ($fullname->result() as $key => $F): ?>

   	<?php
if($notification != false)
  foreach ($notification->result() as $key => $Q): ?>

		
      
                <!-- Notifications -->
                <li class="dropdown notifications">
			
                <a id="<?php echo $Q->id; ?>" href="#"  <?php if ($Q->seen ==0){echo'class="dropdown-toggle" ;' ;}?> data-toggle="dropdown">
				
			<i class="fa fa-fw fa-bell-o"></i>
                    </a>
	
                    <ul class="dropdown-menu">
                        <li class="media notification">
                            <a class="pull-left" href="#">
                                <img  class="img-notification" src="<?php echo base_url('/public/user/uploads/avatars/'.$Q->img); ?>" alt="people">
								
                            </a>
                          <div id="noti" class="media-body">
                                <span class="label label-default pull-right">5 min</span>
                                <h5 class="media-heading"><?php echo $Q->fullname; ?></h5>
                                <p class="margin-none">  <i class="fa fa-fw fa-user"></i> Join your mind !</p>
                            </div>
                        </li>
                  		
</ul>
   </li>
  
             
 <?php endforeach;?>

				

				 
            </ul>
			
		
		
	

            <ul class="nav navbar-nav navbar-user">
			

                <!-- User -->
                <li class="dropdown">
				
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="<?php echo base_url('/public/user/uploads/avatars/'.$F->img_thumb);?>"  class="img-circle" />  <i class="fa fa-fw icon-lock "></i> <i class="fa fa-fw fa-angle-down"></i>  
			
					
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="<?php echo base_url('index.php/@'.$F->username);?>">Profile</a>
                        </li>
                        <li><a  class="error" href="#">Messages</a>
                        </li>

                        <li><a href="<?php echo base_url('index.php/home/logout');?>">Logout</a>
                        </li>
                    </ul>
                </li>
            </ul>
		<script>
		// Generated by CoffeeScript 1.9.2
(function() {
  $(function() {
    $.growl({
      title: "Welcome !",
      message: "Welcome to Napdo Beta test"
    });
    $('.error').click(function(event) {
      event.preventDefault();
      event.stopPropagation();
      return $.growl.error({
        message: "Page under construction, coming soon !"
      });
    });
    $('.notice').click(function(event) {
      event.preventDefault();
      event.stopPropagation();
      return $.growl.notice({
        message: "The kitten is cute!"
      });
    });
    return $('.warning').click(function(event) {
      event.preventDefault();
      event.stopPropagation();
      return $.growl.warning({
        message: "The kitten is ugly!"
      });
    });
  });

}).call(this);
		</script>

            <ul class="nav navbar-nav hidden-xs">
  <?php endforeach;?>



 			<script type="text/javascript" >
$(function() 
{
$(".notifications").click(function(){
	var element = $(this);
var I = element.attr("id");
var info = 'id=' + I; 

$.ajax({
type: "POST",
url: "<?php echo base_url('home/update_notification');?>",
data: info,
success: function(success){

       
      $('.dropdow-menu').css("display","");  
      $('.dropdownmenu').html("");  
	 

}
});
return false;
});
});
</script>
                <!-- Search -->
			
                <div class="input-group pull-left">
                    <span class="input-group-addon"><i class="icon-search"></i></span>
                    <input id="search_box" autocomplete="on" spellcheck="false" type="text" class="form-control" placeholder="Search an idea"/>

                </div>
				
	
                <div class="pull-left visible-md visible-lg" data-toggle="tooltip" data-placement="bottom" title="Alkl">
             
                </div>
            </ul>
            <ul class="nav navbar-nav navbar-right">
			   <li class="pull-right">
                    <a href="#" data-toggle="sidebar-chat">
                        <i class="fa fa-comments"></i>
                    </a>
                </li>
			
			
				<script>
				
	$(function() {
		$('#show').avgrund({
			height: 200,
			holderClass: 'custom',
			showClose: true,
			showCloseText: 'Close',
			enableStackAnimation: true,
			onBlurContainer: '.container',
			template: '<p>So implement your design and place content here! If you want to close modal, please hit "Esc", click somewhere on the screen or use special button.</p>' +
			'<div>' +
			'<a href="http://github.com/voronianski/jquery.avgrund.js" target="_blank" class="github">Avgrund on Github</a>' +
			'<a href="http://twitter.com/voronianski" target="_blank" class="twitter">Twitter</a>' +
			'<a href="http://dribbble.com/voronianski" target="_blank" class="dribble">Dribbble</a>' +
			'</div>'
		});
	});
	
	</script>

  
			
                <li class="pull-right">
                <a id="show" href="#" >
                        <i  class="fa fa-lightbulb-o"></i>
                    </a>
                </li>
			

				 
			
				
			
				
             </ul>
       
			</div>
			
			</div>